# Generated by Django 4.1.7 on 2023-05-15 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AddItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField(max_length=255)),
                ("Name", models.TextField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("s_desc", models.TextField(max_length=255)),
                ("p_desc", models.TextField(max_length=255)),
                ("creat", models.CharField(max_length=255)),
                ("s_price", models.CharField(max_length=255)),
                ("p_price", models.TextField(max_length=255)),
                ("satus", models.TextField(default="active")),
                ("interstate", models.CharField(max_length=255)),
                ("intrastate", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Account_type", models.TextField(max_length=255)),
                ("Account_name", models.TextField(max_length=255)),
                ("Acount_code", models.TextField(max_length=255)),
                ("Account_desc", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Account_type", models.TextField(max_length=255)),
                ("Account_name", models.TextField(max_length=255)),
                ("Acount_code", models.TextField(max_length=255)),
                ("Account_desc", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="vendor_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salutation", models.CharField(max_length=25)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=150)),
                ("vendor_display_name", models.CharField(max_length=150)),
                ("vendor_email", models.CharField(max_length=250)),
                ("vendor_wphone", models.CharField(max_length=50)),
                ("vendor_mphone", models.CharField(max_length=50)),
                ("skype_number", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("website", models.CharField(max_length=250)),
                ("gst_treatment", models.CharField(max_length=100)),
                ("gst_number", models.CharField(max_length=50, null=True)),
                ("pan_number", models.CharField(max_length=50, null=True)),
                ("source_supply", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=50)),
                ("opening_bal", models.CharField(max_length=100)),
                ("payment_terms", models.CharField(max_length=100)),
                ("battention", models.CharField(max_length=100)),
                ("bcountry", models.CharField(max_length=100)),
                ("baddress", models.CharField(max_length=300)),
                ("bcity", models.CharField(max_length=100)),
                ("bstate", models.CharField(max_length=100)),
                ("bzip", models.CharField(max_length=100)),
                ("bphone", models.CharField(max_length=100)),
                ("bfax", models.CharField(max_length=100)),
                ("sattention", models.CharField(max_length=100)),
                ("scountry", models.CharField(max_length=100)),
                ("saddress", models.CharField(max_length=300)),
                ("scity", models.CharField(max_length=100)),
                ("sstate", models.CharField(max_length=100)),
                ("szip", models.CharField(max_length=100)),
                ("sphone", models.CharField(max_length=100)),
                ("sfax", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="remarks_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remarks", models.CharField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zohoapp.vendor_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("message", models.CharField(max_length=255)),
                (
                    "p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zohoapp.additem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_name", models.CharField(max_length=255)),
                ("repeat_every", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("ends_on", models.DateField()),
                ("expense_account", models.CharField(max_length=255)),
                ("expense_type", models.CharField(max_length=50)),
                ("goods_label", models.CharField(default="Unknown", max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=10)),
                ("paidthrough", models.CharField(max_length=50)),
                ("gst", models.CharField(max_length=2551)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zohoapp.vendor_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="contact_person_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salutation", models.CharField(max_length=25)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=200)),
                ("work_phone", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=50)),
                ("skype_number", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zohoapp.vendor_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="company_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.IntegerField(blank=True, null=True)),
                (
                    "company_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "industry_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="image/patient"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="additem",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="zohoapp.purchase"
            ),
        ),
        migrations.AddField(
            model_name="additem",
            name="sales",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="zohoapp.sales"
            ),
        ),
        migrations.AddField(
            model_name="additem",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="zohoapp.unit"
            ),
        ),
        migrations.AddField(
            model_name="additem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
