# Generated by Django 4.1.7 on 2023-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0002_alter_expense_gst"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="goods_label",
            field=models.CharField(default="", max_length=255),
        ),
    ]
