# Generated by Django 4.1.7 on 2023-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0003_alter_expense_goods_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="gst",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
