# Generated by Django 4.1.7 on 2023-05-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0004_alter_expense_gst"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="customername",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="destination",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="notes",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="tax",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
