# Generated by Django 4.1.7 on 2023-05-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0004_remove_additem_tax_additem_interstate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_name", models.CharField(max_length=200)),
                ("repeat_every", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("ends_on", models.DateField()),
                ("expense_account", models.CharField(max_length=200)),
                ("expense_type", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=20)),
                ("paidthrough", models.CharField(max_length=200)),
                ("vendor", models.CharField(max_length=200)),
                ("gsttreatment", models.CharField(max_length=200)),
                ("destination", models.CharField(max_length=200)),
                ("tax", models.CharField(max_length=200)),
                ("notes", models.CharField(max_length=200)),
                ("customername", models.CharField(max_length=200)),
            ],
        ),
    ]
