# Generated by Django 4.1.7 on 2023-05-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0006_vendor_table_remarks_table_contact_person_table_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense", old_name="vendor", new_name="vendorname",
        ),
    ]
