# Generated by Django 4.1.7 on 2023-05-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0006_vendor_table_name_alter_expense_customername_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accountType", models.CharField(max_length=255)),
                ("accountName", models.CharField(max_length=255)),
                ("accountCode", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
