# Generated by Django 4.1.7 on 2023-05-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0007_rename_vendor_expense_vendorname"),
    ]

    operations = [
        migrations.RemoveField(model_name="remarks_table", name="user",),
        migrations.RemoveField(model_name="remarks_table", name="vendor",),
        migrations.RenameField(
            model_name="expense", old_name="vendorname", new_name="name",
        ),
        migrations.DeleteModel(name="contact_person_table",),
        migrations.DeleteModel(name="remarks_table",),
    ]
