# Generated by Django 4.1.7 on 2023-05-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0008_remove_remarks_table_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense", old_name="name", new_name="vendor",
        ),
    ]
