# Generated by Django 4.1.7 on 2023-05-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0011_delete_vendor_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="vendor",
            field=models.CharField(db_column="unique_vendor_key", max_length=200),
        ),
    ]
