# Generated by Django 4.1.7 on 2023-05-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0013_alter_expense_vendor"),
    ]

    operations = [
        migrations.RemoveField(model_name="expense", name="vendor",),
    ]
