# Generated by Django 4.1.7 on 2023-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zohoapp", "0014_remove_expense_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="vendor",
            field=models.CharField(default="", max_length=255),
        ),
    ]
